sudo: required
services:
    - docker

before_install:
    - docker build -t punchaal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true punchaal/docker-react npm run test

deploy: 
    provider: elasticbeanstalk
    region: "ca-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ca-central-1-510584265424"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY